### PR TITLE
Couple of additions

### PR DESCRIPTION
**Pull request by Xanaxiel**
Did some refactoring to make code more readable.

Included Marketnames integration, fixed spacing for stats as well as made stats more descriptive (seen below)

image

### CODE REVIEW

**Comment by Xanaxiel** [comment]
I'll clean this up later and fix these merge conflicts as well (if I get the time), too tired (and lazy from playing ToS) lol. Could also be expanded to show Awakening bonuses on Armor/Weapons/Accessories.

**Comment by Riunia** [comment]
Awakening Bonus would be great, although it looks cluttered as is right now though I'm sure you can fix that.

**Comment by Xanaxiel** [comment]
It looks cluttered because the `text-align` fucks it up (been playing around with it all morning to no avail, it still uses `"center","center"`), so I just did some sort of a workaround with spaces which still makes it look presentable regardless of 1 - 3 properties. 

Probably best to make it configurable as well (like show only properties which the user wants to see, as well as the values)

**Comment by torahamu** [comment]
マージ元のソースはv1.0.2だと思います。
v1.0.4でソースの内容を大幅に変更してしまったため、こちらでマージをしました。
v1.0.5で画像のように、ジェムやヘアアクセサリのオプションの位置を修正しました。
Marketnamesにも対応しています。
取得して確認してみてください。

----

Sorry for Google translation.  
I think the source of the merge source is v1.0.2.  
Since v1.0.4 changed the content of the source greatly, we merged here.  
Fixed the position of options of gems and hair accessories like images in v1.0.5.  
It also supports Marketnames.  
Please get it and check it.  
jemu
hair

**Comment by torahamu** [comment]
ごめんなさい、次は気を付けます。  
v1.0.5で修正完了したので、このPull RequestをCloseします。  

----

Sorry, I will be careful next.  
Since the correction is completed with v1.0.5, Close this Pull Request.

**Pull request closed without merging**
